# Generated by Django 5.2.1 on 2025-07-04 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_tipogasto_remove_doctor_duracion_cita_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='direccion',
            field=models.CharField(help_text='Ubicación física donde atiende el doctor.', max_length=255, verbose_name='Dirección de Trabajo'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='ruc',
            field=models.CharField(help_text='Ingrese un RUC válido (persona natural, sociedad o extranjero).', max_length=13, unique=True, verbose_name='Ruc'),
        ),
    ]
