# Generated by Django 5.2.1 on 2025-07-02 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0005_remove_atencion_doctor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pago',
            name='paypal_order_id',
            field=models.CharField(blank=True, help_text='ID especifico de la orden de paypal para tracking', max_length=100, null=True, verbose_name='ID Orden Paypal'),
        ),
        migrations.AlterField(
            model_name='pago',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('pagado', 'Pagado'), ('fallido', 'Fallido'), ('cancelado', 'Cancelado')], default='pendiente', max_length=20, verbose_name='Estado'),
        ),
    ]
