# Generated by Django 5.2.1 on 2025-07-02 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0006_pago_paypal_order_id_alter_pago_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='pago',
            name='monto_consulta',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Monto correspondiente a la consulta médica', max_digits=10, verbose_name='Monto Consulta'),
        ),
    ]
