# Generated by Django 5.2.1 on 2025-07-02 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0007_pago_monto_consulta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pago',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('pagado', 'Pagado'), ('cancelado', 'Cancelado'), ('fallido', 'Fallido')], default='pendiente', max_length=20, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='pago',
            name='metodo_pago',
            field=models.CharField(choices=[('efectivo', 'Efectivo'), ('paypal', 'PayPal'), ('tarjeta', 'Tarjeta de Crédito/Débito'), ('transferencia', 'Transferencia Bancaria')], default='efectivo', max_length=20, verbose_name='Método de Pago'),
        ),
    ]
