# Generated by Django 5.2.1 on 2025-07-03 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0008_alter_pago_estado_alter_pago_metodo_pago'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pago',
            name='monto_consulta',
        ),
        migrations.RemoveField(
            model_name='pago',
            name='paypal_order_id',
        ),
        migrations.AlterField(
            model_name='pago',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('pagado', 'Pagado'), ('cancelado', 'Cancelado'), ('reembolsado', 'Reembolsado')], default='pendiente', max_length=20, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='pago',
            name='metodo_pago',
            field=models.CharField(choices=[('efectivo', 'Efectivo'), ('paypal', 'PayPal'), ('tarjeta', 'Tarjeta de Crédito/Débito'), ('transferencia', 'Transferencia Bancaria')], max_length=20, verbose_name='Método de Pago'),
        ),
    ]
