# Generated by Django 5.2.1 on 2025-07-04 08:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_doctor_direccion_alter_doctor_ruc'),
        ('doctor', '0009_remove_pago_monto_consulta_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pago',
            name='monto_consulta',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Monto de Consulta'),
        ),
        migrations.AddField(
            model_name='pago',
            name='paciente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pagos_directos', to='core.paciente', verbose_name='Paciente'),
        ),
    ]
